name:                webserver
version:             0.1.0.0
github:              "githubuser/webserver"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2026 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/webserver#readme>

dependencies:
  - base >= 4.14 && < 5
  - bytestring
  - network
  - attoparsec
  - case-insensitive
  - wai
  - warp
  - http-types
  - text
  - directory
  - filepath

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  - OverloadedStrings
  - NumericUnderscores

library:
  source-dirs: src
  exposed-modules:
    - Lib
    - Server
    - Http.Types
    - Http.Parse
    - Http.Response
    - Workloads

executables:
  webserver-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - webserver
    ghc-options:
      - -O2
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  warp-baseline:
    main: Main.hs
    source-dirs: app-warp
    dependencies:
      - webserver
      - wai
      - warp
      - http-types
      - text
    ghc-options:
      - -O2
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N


tests:
  webserver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -O2
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webserver
    - bytestring
    - network
