worker_processes 1;
pid nginx.pid;
error_log stderr warn;

events {
    worker_connections 1024;
}

http {
    access_log off;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 8083;
        server_name localhost;

        location = / {
            default_type text/plain;
            return 200 "ok\n";
        }

        location = /health {
            default_type text/plain;
            return 200 "healthy\n";
        }

        location = /json {
            alias __STATIC_ROOT__/json1k.json;
            default_type application/json;
        }

        location = /file50k {
            alias __STATIC_ROOT__/file50k.bin;
            default_type application/octet-stream;
        }

        location = /file1m {
            alias __STATIC_ROOT__/file1m.bin;
            default_type application/octet-stream;
        }

        location / {
            default_type text/plain;
            return 404 "not found\n";
        }
    }
}
